// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

// swiftlint:disable all
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(affine_mobile_nativeFFI)
import affine_mobile_nativeFFI
#endif

fileprivate extension RustBuffer {
    // Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func empty() -> RustBuffer {
        RustBuffer(capacity: 0, len:0, data: nil)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_affine_mobile_native_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    // Frees the buffer in place.
    // The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_affine_mobile_native_rustbuffer_free(self, $0) }
    }
}

fileprivate extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

fileprivate extension Data {
    init(rustBuffer: RustBuffer) {
        self.init(
            bytesNoCopy: rustBuffer.data!,
            count: Int(rustBuffer.len),
            deallocator: .none
        )
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

fileprivate func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

// Reads an integer at the current offset, in big-endian order, and advances
// the offset on success. Throws if reading the integer would move the
// offset past the end of the buffer.
fileprivate func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset..<reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value, { reader.data.copyBytes(to: $0, from: range)})
    reader.offset = range.upperBound
    return value.bigEndian
}

// Reads an arbitrary number of bytes, to be used to read
// raw bytes, this is useful when lifting strings
fileprivate func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> Array<UInt8> {
    let range = reader.offset..<(reader.offset+count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer({ buffer in
        reader.data.copyBytes(to: buffer, from: range)
    })
    reader.offset = range.upperBound
    return value
}

// Reads a float at the current offset.
fileprivate func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return Float(bitPattern: try readInt(&reader))
}

// Reads a float at the current offset.
fileprivate func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return Double(bitPattern: try readInt(&reader))
}

// Indicates if the offset has reached the end of the buffer.
fileprivate func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

fileprivate func createWriter() -> [UInt8] {
    return []
}

fileprivate func writeBytes<S>(_ writer: inout [UInt8], _ byteArr: S) where S: Sequence, S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

// Writes an integer in big-endian order.
//
// Warning: make sure what you are trying to write
// is in the correct type!
fileprivate func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

fileprivate func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

fileprivate func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

// Protocol for types that transfer other types across the FFI. This is
// analogous to the Rust trait of the same name.
fileprivate protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

// Types conforming to `Primitive` pass themselves directly over the FFI.
fileprivate protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType { }

extension FfiConverterPrimitive {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
// Used for complex types where it's hard to write a custom lift/lower.
fileprivate protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> RustBuffer {
          var writer = createWriter()
          write(value, into: &writer)
          return RustBuffer(bytes: writer)
    }
}
// An error type for FFI errors. These errors occur at the UniFFI level, not
// the library level.
fileprivate enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    public var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

fileprivate extension NSLock {
    func withLock<T>(f: () throws -> T) rethrows -> T {
        self.lock()
        defer { self.unlock() }
        return try f()
    }
}

fileprivate let CALL_SUCCESS: Int8 = 0
fileprivate let CALL_ERROR: Int8 = 1
fileprivate let CALL_UNEXPECTED_ERROR: Int8 = 2
fileprivate let CALL_CANCELLED: Int8 = 3

fileprivate extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer.init(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    let neverThrow: ((RustBuffer) throws -> Never)? = nil
    return try makeRustCall(callback, errorHandler: neverThrow)
}

private func rustCallWithError<T, E: Swift.Error>(
    _ errorHandler: @escaping (RustBuffer) throws -> E,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T, E: Swift.Error>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> E)?
) throws -> T {
    uniffiEnsureInitialized()
    var callStatus = RustCallStatus.init()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus<E: Swift.Error>(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> E)?
) throws {
    switch callStatus.code {
        case CALL_SUCCESS:
            return

        case CALL_ERROR:
            if let errorHandler = errorHandler {
                throw try errorHandler(callStatus.errorBuf)
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.unexpectedRustCallError
            }

        case CALL_UNEXPECTED_ERROR:
            // When the rust code sees a panic, it tries to construct a RustBuffer
            // with the message.  But if that code panics, then it just sends back
            // an empty buffer.
            if callStatus.errorBuf.len > 0 {
                throw UniffiInternalError.rustPanic(try FfiConverterString.lift(callStatus.errorBuf))
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.rustPanic("Rust panic")
            }

        case CALL_CANCELLED:
            fatalError("Cancellation not supported yet")

        default:
            throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

private func uniffiTraitInterfaceCall<T>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> ()
) {
    do {
        try writeReturn(makeCall())
    } catch let error {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private func uniffiTraitInterfaceCallWithError<T, E>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> (),
    lowerError: (E) -> RustBuffer
) {
    do {
        try writeReturn(makeCall())
    } catch let error as E {
        callStatus.pointee.code = CALL_ERROR
        callStatus.pointee.errorBuf = lowerError(error)
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}
fileprivate class UniffiHandleMap<T> {
    private var map: [UInt64: T] = [:]
    private let lock = NSLock()
    private var currentHandle: UInt64 = 1

    func insert(obj: T) -> UInt64 {
        lock.withLock {
            let handle = currentHandle
            currentHandle += 1
            map[handle] = obj
            return handle
        }
    }

     func get(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    @discardableResult
    func remove(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map.removeValue(forKey: handle) else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    var count: Int {
        get {
            map.count
        }
    }
}


// Public interface members begin here.


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt32: FfiConverterPrimitive {
    typealias FfiType = UInt32
    typealias SwiftType = UInt32

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt32 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterBool : FfiConverter {
    typealias FfiType = Int8
    typealias SwiftType = Bool

    public static func lift(_ value: Int8) throws -> Bool {
        return value != 0
    }

    public static func lower(_ value: Bool) -> Int8 {
        return value ? 1 : 0
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Bool {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Bool, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    public static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        return String(bytes: bytes, encoding: String.Encoding.utf8)!
    }

    public static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        return String(bytes: try readBytes(&buf, count: Int(len)), encoding: String.Encoding.utf8)!
    }

    public static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterData: FfiConverterRustBuffer {
    typealias SwiftType = Data

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Data {
        let len: Int32 = try readInt(&buf)
        return Data(try readBytes(&buf, count: Int(len)))
    }

    public static func write(_ value: Data, into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        writeBytes(&buf, value)
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterTimestamp: FfiConverterRustBuffer {
    typealias SwiftType = Date

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Date {
        let seconds: Int64 = try readInt(&buf)
        let nanoseconds: UInt32 = try readInt(&buf)
        if seconds >= 0 {
            let delta = Double(seconds) + (Double(nanoseconds) / 1.0e9)
            return Date.init(timeIntervalSince1970: delta)
        } else {
            let delta = Double(seconds) - (Double(nanoseconds) / 1.0e9)
            return Date.init(timeIntervalSince1970: delta)
        }
    }

    public static func write(_ value: Date, into buf: inout [UInt8]) {
        var delta = value.timeIntervalSince1970
        var sign: Int64 = 1
        if delta < 0 {
            // The nanoseconds portion of the epoch offset must always be
            // positive, to simplify the calculation we will use the absolute
            // value of the offset.
            sign = -1
            delta = -delta
        }
        if delta.rounded(.down) > Double(Int64.max) {
            fatalError("Timestamp overflow, exceeds max bounds supported by Uniffi")
        }
        let seconds = Int64(delta)
        let nanoseconds = UInt32((delta - Double(seconds)) * 1.0e9)
        writeInt(&buf, sign * seconds)
        writeInt(&buf, nanoseconds)
    }
}




public protocol DocStorageProtocol : AnyObject {
    
    func checkpoint() async throws 
    
    func close() async throws 
    
    /**
     * Initialize the database and run migrations.
     */
    func connect() async throws 
    
    func deleteDoc(docId: String) async throws 
    
    func getDocClock(docId: String) async throws  -> DocClock?
    
    func getDocClocks(after: Date?) async throws  -> [DocClock]
    
    func getDocSnapshot(docId: String) async throws  -> DocRecord?
    
    func getDocUpdates(docId: String) async throws  -> [DocUpdate]
    
    func isClosed()  -> Bool
    
    func markUpdatesMerged(docId: String, updates: [Date]) async throws  -> UInt32
    
    func pushUpdate(docId: String, update: Data) async throws  -> Date
    
    func setDocSnapshot(snapshot: DocRecord) async throws  -> Bool
    
    func setSpaceId(spaceId: String) async throws 
    
    func validate() async throws  -> Bool
    
}

open class DocStorage:
    DocStorageProtocol {
    fileprivate let pointer: UnsafeMutableRawPointer!

    /// Used to instantiate a [FFIObject] without an actual pointer, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoPointer {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
    required public init(unsafeFromRawPointer pointer: UnsafeMutableRawPointer) {
        self.pointer = pointer
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noPointer: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing [Pointer] the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noPointer: NoPointer) {
        self.pointer = nil
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiClonePointer() -> UnsafeMutableRawPointer {
        return try! rustCall { uniffi_affine_mobile_native_fn_clone_docstorage(self.pointer, $0) }
    }
public convenience init(path: String)throws  {
    let pointer =
        try rustCallWithError(FfiConverterTypeUniffiError.lift) {
    uniffi_affine_mobile_native_fn_constructor_docstorage_new(
        FfiConverterString.lower(path),$0
    )
}
    self.init(unsafeFromRawPointer: pointer)
}

    deinit {
        guard let pointer = pointer else {
            return
        }

        try! rustCall { uniffi_affine_mobile_native_fn_free_docstorage(pointer, $0) }
    }

    

    
open func checkpoint()async throws  {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_affine_mobile_native_fn_method_docstorage_checkpoint(
                    self.uniffiClonePointer()
                    
                )
            },
            pollFunc: ffi_affine_mobile_native_rust_future_poll_void,
            completeFunc: ffi_affine_mobile_native_rust_future_complete_void,
            freeFunc: ffi_affine_mobile_native_rust_future_free_void,
            liftFunc: { $0 },
            errorHandler: FfiConverterTypeUniffiError.lift
        )
}
    
open func close()async throws  {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_affine_mobile_native_fn_method_docstorage_close(
                    self.uniffiClonePointer()
                    
                )
            },
            pollFunc: ffi_affine_mobile_native_rust_future_poll_void,
            completeFunc: ffi_affine_mobile_native_rust_future_complete_void,
            freeFunc: ffi_affine_mobile_native_rust_future_free_void,
            liftFunc: { $0 },
            errorHandler: FfiConverterTypeUniffiError.lift
        )
}
    
    /**
     * Initialize the database and run migrations.
     */
open func connect()async throws  {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_affine_mobile_native_fn_method_docstorage_connect(
                    self.uniffiClonePointer()
                    
                )
            },
            pollFunc: ffi_affine_mobile_native_rust_future_poll_void,
            completeFunc: ffi_affine_mobile_native_rust_future_complete_void,
            freeFunc: ffi_affine_mobile_native_rust_future_free_void,
            liftFunc: { $0 },
            errorHandler: FfiConverterTypeUniffiError.lift
        )
}
    
open func deleteDoc(docId: String)async throws  {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_affine_mobile_native_fn_method_docstorage_delete_doc(
                    self.uniffiClonePointer(),
                    FfiConverterString.lower(docId)
                )
            },
            pollFunc: ffi_affine_mobile_native_rust_future_poll_void,
            completeFunc: ffi_affine_mobile_native_rust_future_complete_void,
            freeFunc: ffi_affine_mobile_native_rust_future_free_void,
            liftFunc: { $0 },
            errorHandler: FfiConverterTypeUniffiError.lift
        )
}
    
open func getDocClock(docId: String)async throws  -> DocClock? {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_affine_mobile_native_fn_method_docstorage_get_doc_clock(
                    self.uniffiClonePointer(),
                    FfiConverterString.lower(docId)
                )
            },
            pollFunc: ffi_affine_mobile_native_rust_future_poll_rust_buffer,
            completeFunc: ffi_affine_mobile_native_rust_future_complete_rust_buffer,
            freeFunc: ffi_affine_mobile_native_rust_future_free_rust_buffer,
            liftFunc: FfiConverterOptionTypeDocClock.lift,
            errorHandler: FfiConverterTypeUniffiError.lift
        )
}
    
open func getDocClocks(after: Date?)async throws  -> [DocClock] {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_affine_mobile_native_fn_method_docstorage_get_doc_clocks(
                    self.uniffiClonePointer(),
                    FfiConverterOptionTimestamp.lower(after)
                )
            },
            pollFunc: ffi_affine_mobile_native_rust_future_poll_rust_buffer,
            completeFunc: ffi_affine_mobile_native_rust_future_complete_rust_buffer,
            freeFunc: ffi_affine_mobile_native_rust_future_free_rust_buffer,
            liftFunc: FfiConverterSequenceTypeDocClock.lift,
            errorHandler: FfiConverterTypeUniffiError.lift
        )
}
    
open func getDocSnapshot(docId: String)async throws  -> DocRecord? {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_affine_mobile_native_fn_method_docstorage_get_doc_snapshot(
                    self.uniffiClonePointer(),
                    FfiConverterString.lower(docId)
                )
            },
            pollFunc: ffi_affine_mobile_native_rust_future_poll_rust_buffer,
            completeFunc: ffi_affine_mobile_native_rust_future_complete_rust_buffer,
            freeFunc: ffi_affine_mobile_native_rust_future_free_rust_buffer,
            liftFunc: FfiConverterOptionTypeDocRecord.lift,
            errorHandler: FfiConverterTypeUniffiError.lift
        )
}
    
open func getDocUpdates(docId: String)async throws  -> [DocUpdate] {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_affine_mobile_native_fn_method_docstorage_get_doc_updates(
                    self.uniffiClonePointer(),
                    FfiConverterString.lower(docId)
                )
            },
            pollFunc: ffi_affine_mobile_native_rust_future_poll_rust_buffer,
            completeFunc: ffi_affine_mobile_native_rust_future_complete_rust_buffer,
            freeFunc: ffi_affine_mobile_native_rust_future_free_rust_buffer,
            liftFunc: FfiConverterSequenceTypeDocUpdate.lift,
            errorHandler: FfiConverterTypeUniffiError.lift
        )
}
    
open func isClosed() -> Bool {
    return try!  FfiConverterBool.lift(try! rustCall() {
    uniffi_affine_mobile_native_fn_method_docstorage_is_closed(self.uniffiClonePointer(),$0
    )
})
}
    
open func markUpdatesMerged(docId: String, updates: [Date])async throws  -> UInt32 {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_affine_mobile_native_fn_method_docstorage_mark_updates_merged(
                    self.uniffiClonePointer(),
                    FfiConverterString.lower(docId),FfiConverterSequenceTimestamp.lower(updates)
                )
            },
            pollFunc: ffi_affine_mobile_native_rust_future_poll_u32,
            completeFunc: ffi_affine_mobile_native_rust_future_complete_u32,
            freeFunc: ffi_affine_mobile_native_rust_future_free_u32,
            liftFunc: FfiConverterUInt32.lift,
            errorHandler: FfiConverterTypeUniffiError.lift
        )
}
    
open func pushUpdate(docId: String, update: Data)async throws  -> Date {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_affine_mobile_native_fn_method_docstorage_push_update(
                    self.uniffiClonePointer(),
                    FfiConverterString.lower(docId),FfiConverterData.lower(update)
                )
            },
            pollFunc: ffi_affine_mobile_native_rust_future_poll_rust_buffer,
            completeFunc: ffi_affine_mobile_native_rust_future_complete_rust_buffer,
            freeFunc: ffi_affine_mobile_native_rust_future_free_rust_buffer,
            liftFunc: FfiConverterTimestamp.lift,
            errorHandler: FfiConverterTypeUniffiError.lift
        )
}
    
open func setDocSnapshot(snapshot: DocRecord)async throws  -> Bool {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_affine_mobile_native_fn_method_docstorage_set_doc_snapshot(
                    self.uniffiClonePointer(),
                    FfiConverterTypeDocRecord.lower(snapshot)
                )
            },
            pollFunc: ffi_affine_mobile_native_rust_future_poll_i8,
            completeFunc: ffi_affine_mobile_native_rust_future_complete_i8,
            freeFunc: ffi_affine_mobile_native_rust_future_free_i8,
            liftFunc: FfiConverterBool.lift,
            errorHandler: FfiConverterTypeUniffiError.lift
        )
}
    
open func setSpaceId(spaceId: String)async throws  {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_affine_mobile_native_fn_method_docstorage_set_space_id(
                    self.uniffiClonePointer(),
                    FfiConverterString.lower(spaceId)
                )
            },
            pollFunc: ffi_affine_mobile_native_rust_future_poll_void,
            completeFunc: ffi_affine_mobile_native_rust_future_complete_void,
            freeFunc: ffi_affine_mobile_native_rust_future_free_void,
            liftFunc: { $0 },
            errorHandler: FfiConverterTypeUniffiError.lift
        )
}
    
open func validate()async throws  -> Bool {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_affine_mobile_native_fn_method_docstorage_validate(
                    self.uniffiClonePointer()
                    
                )
            },
            pollFunc: ffi_affine_mobile_native_rust_future_poll_i8,
            completeFunc: ffi_affine_mobile_native_rust_future_complete_i8,
            freeFunc: ffi_affine_mobile_native_rust_future_free_i8,
            liftFunc: FfiConverterBool.lift,
            errorHandler: FfiConverterTypeUniffiError.lift
        )
}
    

}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeDocStorage: FfiConverter {

    typealias FfiType = UnsafeMutableRawPointer
    typealias SwiftType = DocStorage

    public static func lift(_ pointer: UnsafeMutableRawPointer) throws -> DocStorage {
        return DocStorage(unsafeFromRawPointer: pointer)
    }

    public static func lower(_ value: DocStorage) -> UnsafeMutableRawPointer {
        return value.uniffiClonePointer()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> DocStorage {
        let v: UInt64 = try readInt(&buf)
        // The Rust code won't compile if a pointer won't fit in a UInt64.
        // We have to go via `UInt` because that's the thing that's the size of a pointer.
        let ptr = UnsafeMutableRawPointer(bitPattern: UInt(truncatingIfNeeded: v))
        if (ptr == nil) {
            throw UniffiInternalError.unexpectedNullPointer
        }
        return try lift(ptr!)
    }

    public static func write(_ value: DocStorage, into buf: inout [UInt8]) {
        // This fiddling is because `Int` is the thing that's the same size as a pointer.
        // The Rust code won't compile if a pointer won't fit in a `UInt64`.
        writeInt(&buf, UInt64(bitPattern: Int64(Int(bitPattern: lower(value)))))
    }
}




#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeDocStorage_lift(_ pointer: UnsafeMutableRawPointer) throws -> DocStorage {
    return try FfiConverterTypeDocStorage.lift(pointer)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeDocStorage_lower(_ value: DocStorage) -> UnsafeMutableRawPointer {
    return FfiConverterTypeDocStorage.lower(value)
}


public struct DocClock {
    public var docId: String
    public var timestamp: Date

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(docId: String, timestamp: Date) {
        self.docId = docId
        self.timestamp = timestamp
    }
}



extension DocClock: Equatable, Hashable {
    public static func ==(lhs: DocClock, rhs: DocClock) -> Bool {
        if lhs.docId != rhs.docId {
            return false
        }
        if lhs.timestamp != rhs.timestamp {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(docId)
        hasher.combine(timestamp)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeDocClock: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> DocClock {
        return
            try DocClock(
                docId: FfiConverterString.read(from: &buf), 
                timestamp: FfiConverterTimestamp.read(from: &buf)
        )
    }

    public static func write(_ value: DocClock, into buf: inout [UInt8]) {
        FfiConverterString.write(value.docId, into: &buf)
        FfiConverterTimestamp.write(value.timestamp, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeDocClock_lift(_ buf: RustBuffer) throws -> DocClock {
    return try FfiConverterTypeDocClock.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeDocClock_lower(_ value: DocClock) -> RustBuffer {
    return FfiConverterTypeDocClock.lower(value)
}


public struct DocRecord {
    public var docId: String
    public var data: Data
    public var timestamp: Date

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(docId: String, data: Data, timestamp: Date) {
        self.docId = docId
        self.data = data
        self.timestamp = timestamp
    }
}



extension DocRecord: Equatable, Hashable {
    public static func ==(lhs: DocRecord, rhs: DocRecord) -> Bool {
        if lhs.docId != rhs.docId {
            return false
        }
        if lhs.data != rhs.data {
            return false
        }
        if lhs.timestamp != rhs.timestamp {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(docId)
        hasher.combine(data)
        hasher.combine(timestamp)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeDocRecord: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> DocRecord {
        return
            try DocRecord(
                docId: FfiConverterString.read(from: &buf), 
                data: FfiConverterData.read(from: &buf), 
                timestamp: FfiConverterTimestamp.read(from: &buf)
        )
    }

    public static func write(_ value: DocRecord, into buf: inout [UInt8]) {
        FfiConverterString.write(value.docId, into: &buf)
        FfiConverterData.write(value.data, into: &buf)
        FfiConverterTimestamp.write(value.timestamp, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeDocRecord_lift(_ buf: RustBuffer) throws -> DocRecord {
    return try FfiConverterTypeDocRecord.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeDocRecord_lower(_ value: DocRecord) -> RustBuffer {
    return FfiConverterTypeDocRecord.lower(value)
}


public struct DocUpdate {
    public var docId: String
    public var createdAt: Date
    public var data: Data

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(docId: String, createdAt: Date, data: Data) {
        self.docId = docId
        self.createdAt = createdAt
        self.data = data
    }
}



extension DocUpdate: Equatable, Hashable {
    public static func ==(lhs: DocUpdate, rhs: DocUpdate) -> Bool {
        if lhs.docId != rhs.docId {
            return false
        }
        if lhs.createdAt != rhs.createdAt {
            return false
        }
        if lhs.data != rhs.data {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(docId)
        hasher.combine(createdAt)
        hasher.combine(data)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeDocUpdate: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> DocUpdate {
        return
            try DocUpdate(
                docId: FfiConverterString.read(from: &buf), 
                createdAt: FfiConverterTimestamp.read(from: &buf), 
                data: FfiConverterData.read(from: &buf)
        )
    }

    public static func write(_ value: DocUpdate, into buf: inout [UInt8]) {
        FfiConverterString.write(value.docId, into: &buf)
        FfiConverterTimestamp.write(value.createdAt, into: &buf)
        FfiConverterData.write(value.data, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeDocUpdate_lift(_ buf: RustBuffer) throws -> DocUpdate {
    return try FfiConverterTypeDocUpdate.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeDocUpdate_lower(_ value: DocUpdate) -> RustBuffer {
    return FfiConverterTypeDocUpdate.lower(value)
}


public enum UniffiError {

    
    
    case EmptyDocStoragePath
    case EmptySpaceId
    case SqlxError(String
    )
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeUniffiError: FfiConverterRustBuffer {
    typealias SwiftType = UniffiError

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UniffiError {
        let variant: Int32 = try readInt(&buf)
        switch variant {

        

        
        case 1: return .EmptyDocStoragePath
        case 2: return .EmptySpaceId
        case 3: return .SqlxError(
            try FfiConverterString.read(from: &buf)
            )

         default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: UniffiError, into buf: inout [UInt8]) {
        switch value {

        

        
        
        case .EmptyDocStoragePath:
            writeInt(&buf, Int32(1))
        
        
        case .EmptySpaceId:
            writeInt(&buf, Int32(2))
        
        
        case let .SqlxError(v1):
            writeInt(&buf, Int32(3))
            FfiConverterString.write(v1, into: &buf)
            
        }
    }
}


extension UniffiError: Equatable, Hashable {}

extension UniffiError: Foundation.LocalizedError {
    public var errorDescription: String? {
        String(reflecting: self)
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionTimestamp: FfiConverterRustBuffer {
    typealias SwiftType = Date?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterTimestamp.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterTimestamp.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionTypeDocClock: FfiConverterRustBuffer {
    typealias SwiftType = DocClock?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterTypeDocClock.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterTypeDocClock.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionTypeDocRecord: FfiConverterRustBuffer {
    typealias SwiftType = DocRecord?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterTypeDocRecord.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterTypeDocRecord.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTimestamp: FfiConverterRustBuffer {
    typealias SwiftType = [Date]

    public static func write(_ value: [Date], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTimestamp.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [Date] {
        let len: Int32 = try readInt(&buf)
        var seq = [Date]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTimestamp.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeDocClock: FfiConverterRustBuffer {
    typealias SwiftType = [DocClock]

    public static func write(_ value: [DocClock], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeDocClock.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [DocClock] {
        let len: Int32 = try readInt(&buf)
        var seq = [DocClock]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeDocClock.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeDocUpdate: FfiConverterRustBuffer {
    typealias SwiftType = [DocUpdate]

    public static func write(_ value: [DocUpdate], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeDocUpdate.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [DocUpdate] {
        let len: Int32 = try readInt(&buf)
        var seq = [DocUpdate]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeDocUpdate.read(from: &buf))
        }
        return seq
    }
}
private let UNIFFI_RUST_FUTURE_POLL_READY: Int8 = 0
private let UNIFFI_RUST_FUTURE_POLL_MAYBE_READY: Int8 = 1

fileprivate let uniffiContinuationHandleMap = UniffiHandleMap<UnsafeContinuation<Int8, Never>>()

fileprivate func uniffiRustCallAsync<F, T>(
    rustFutureFunc: () -> UInt64,
    pollFunc: (UInt64, @escaping UniffiRustFutureContinuationCallback, UInt64) -> (),
    completeFunc: (UInt64, UnsafeMutablePointer<RustCallStatus>) -> F,
    freeFunc: (UInt64) -> (),
    liftFunc: (F) throws -> T,
    errorHandler: ((RustBuffer) throws -> Swift.Error)?
) async throws -> T {
    // Make sure to call uniffiEnsureInitialized() since future creation doesn't have a
    // RustCallStatus param, so doesn't use makeRustCall()
    uniffiEnsureInitialized()
    let rustFuture = rustFutureFunc()
    defer {
        freeFunc(rustFuture)
    }
    var pollResult: Int8;
    repeat {
        pollResult = await withUnsafeContinuation {
            pollFunc(
                rustFuture,
                uniffiFutureContinuationCallback,
                uniffiContinuationHandleMap.insert(obj: $0)
            )
        }
    } while pollResult != UNIFFI_RUST_FUTURE_POLL_READY

    return try liftFunc(makeRustCall(
        { completeFunc(rustFuture, $0) },
        errorHandler: errorHandler
    ))
}

// Callback handlers for an async calls.  These are invoked by Rust when the future is ready.  They
// lift the return value or error and resume the suspended function.
fileprivate func uniffiFutureContinuationCallback(handle: UInt64, pollResult: Int8) {
    if let continuation = try? uniffiContinuationHandleMap.remove(handle: handle) {
        continuation.resume(returning: pollResult)
    } else {
        print("uniffiFutureContinuationCallback invalid handle")
    }
}
public func hashcashMint(resource: String, bits: UInt32) -> String {
    return try!  FfiConverterString.lift(try! rustCall() {
    uniffi_affine_mobile_native_fn_func_hashcash_mint(
        FfiConverterString.lower(resource),
        FfiConverterUInt32.lower(bits),$0
    )
})
}

private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}
// Use a global variable to perform the versioning checks. Swift ensures that
// the code inside is only computed once.
private var initializationResult: InitializationResult = {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 26
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_affine_mobile_native_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }
    if (uniffi_affine_mobile_native_checksum_func_hashcash_mint() != 23633) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_affine_mobile_native_checksum_method_docstorage_checkpoint() != 36613) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_affine_mobile_native_checksum_method_docstorage_close() != 10808) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_affine_mobile_native_checksum_method_docstorage_connect() != 15551) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_affine_mobile_native_checksum_method_docstorage_delete_doc() != 53248) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_affine_mobile_native_checksum_method_docstorage_get_doc_clock() != 29534) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_affine_mobile_native_checksum_method_docstorage_get_doc_clocks() != 44204) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_affine_mobile_native_checksum_method_docstorage_get_doc_snapshot() != 9624) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_affine_mobile_native_checksum_method_docstorage_get_doc_updates() != 57795) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_affine_mobile_native_checksum_method_docstorage_is_closed() != 25468) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_affine_mobile_native_checksum_method_docstorage_mark_updates_merged() != 56840) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_affine_mobile_native_checksum_method_docstorage_push_update() != 157) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_affine_mobile_native_checksum_method_docstorage_set_doc_snapshot() != 6431) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_affine_mobile_native_checksum_method_docstorage_set_space_id() != 22706) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_affine_mobile_native_checksum_method_docstorage_validate() != 11413) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_affine_mobile_native_checksum_constructor_docstorage_new() != 48015) {
        return InitializationResult.apiChecksumMismatch
    }

    return InitializationResult.ok
}()

private func uniffiEnsureInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// swiftlint:enable all